src/importer/archetype.js
src/importer/bad.js
src/importer/dollartaco.js
src/importer/lazycaps.js
src/importer/tokkipee.js

Add some missing websites:
- archetype
- bad
- dollartaco
- lazycaps
- tokkipee

Add some missing websites

---

src/importer/unbrandedcaps.js

Here is the catalog https://docs.google.com/document/d/1nQIdjUjkWGyGAIgiEl2oXANX2MJj91uFhCPKOLx2qWw

Add Unbranded.caps

---

src/importer/keycravings.js

Here is the catalog: https://docs.google.com/document/d/1QjFV7yp4Ez8k51qPo2fx_2sXVH9l7SdbI3_sy_E7R_o

Add KeyCravings

---

src/importer/dustycaps.js

Here is the catalog: https://docs.google.com/document/d/1EZstC5O7OMdsCMMzs-YbV3Y5pooytHrHpLWaULr3pEI/edit#

Add DustyCaps catalog

---

package.json
src/generate.js
src/importer/alphakeycaps.js
src/scraper/gdoc.js

This adds the possibility to fallback to current state of catalog instead of having it blocking the whole process.
Still need to have notice on the CI to see if there is errors of not

feat: add possibility to fallback for catalogs

---

src/importer/bobhandcraft.js

Here is the catalog: https://docs.google.com/document/d/1Igk_at2yvP_Bd6GNd3_GLCQmooNszkNDDvm2b6yqIQM/

Add B.o.B Handcraft catalog

---

src/importer/hotkeysproject.js
src/importer/scraft.js

HKP catalog: https://docs.google.com/document/d/1KcZjWQ59gmgNoX1piEdf6MX1r6sBig2_G9AYrs1SjBQ/edit#
S-Craft catalog: https://docs.google.com/document/d/1zM8PAeSNFJ1Voo4m2Qpcjqtymy_umMBBMVt_USkoYCs/edit

Add Hot Key Project and S-Craft catalogs

---

src/importer/girlycaps.js

Catalog: https://docs.google.com/document/d/1cDD3aNsQXHJfyskP8906BUwfc1_4H_JJTtZ9akhQkOc/edit#

Add Girlycaps Studios

---

src/importer/keycat.js

Catalog: https://docs.google.com/document/d/1VNVGf02zR9t3QBYXbxV9SqJFuilQBpKxWHTj0iWrX3w/edit

Add Keycat

---

src/importer/rtgcaps.js

Catalog: https://docs.google.com/document/d/1XNeLhAdqfwbgmpm4qbN9nUFQzLktN0JiEJGgRVCEnpk/

Added rtg_caps_ catalog

---

src/importer/hellbentcaps.js

Catalog link: https://docs.google.com/document/d/15NNk_ttTXCBCHTzyEE3_EigOHPYnc1M5fVGRZJIt0AA/

Added hellbent caps catalog

---

src/importer/slimescholar.js

Catalog: https://docs.google.com/document/d/14jF0ewtoj5S2GPXkGrfppH3zu0Dd2Y8aZnJ_nP1kPuw

Added slime scholar catalog

---

src/importer/craftkey.js

Catalog: https://docs.google.com/document/d/1Ruol_1a4kzgLyXkeQ4d7ayu2shpsJPrHVUu7dBIYOYQ

Added craftkey catalog

---

src/importer/bowbie.js

Catalog: https://docs.google.com/document/d/1CyKhBbny0xMHcbHtdFQC_P0nrczYOpYdz3KV6ujdPnc/

Added bowbie catalog

---

src/importer/dreadkeys.js

Catalog: https://docs.google.com/document/d/1tzm7_NLV5XdM2tuM2naiZhDjMMygstN2XneBU_GWbeY

Added dreadkey catalog

---

src/importer/winkeys.js

Catalog: https://docs.google.com/document/d/1RKX9sVYGkGQKnfGjaLeiFuYwA5zbi5UYfdwSYxHK90w/

added win keys catalog

---

src/importer/krakenkap.js

Catalog: https://docs.google.com/document/d/1zvIUqPg7D-vge_JzpzqmnD4lEkQgzaQCBFc10FXmasA/edit

Add KrakenKap

---

src/importer/kapcave.js

This is my first attempt at writing JS. Instead of doing a bunch of JS to map the API returned dict to the one expected by the generate script, I'm having the API return the exact dict and generating IDs on here to keep them in sync with the rest of the system.

Adding a importer for KapCave which uses the API to fetch catalog

---

src/importer/obscura.js

Catalog: https://docs.google.com/document/d/1nhTGlHevXa6adT_nUrr8aSwt0MevlqlRA3K4_AAr7nE/

Added obscura catalog

---

src/importer/captomaniacs.js

Catalog: https://docs.google.com/document/d/1yy-k0dvNLQtG9syt3gXHEhVLzuDD7nFSmsai7SSpm94/

added captomaniacs catalog

---

src/importer/zycap.js

Catalog: https://docs.google.com/document/d/1iFu8FhwjqIJSrweEA9ziazm0eD5rz3k3NgMtzIHzNw0/

Added zycap catalog

---

src/importer/coconutkeycaps.js

Catalog: https://docs.google.com/document/d/1lx648GXchw4ZpctFtirPx_teQcpcgVWuy83W32JY4KU/

added coconut keycaps catalog

---

src/importer/hungryhustlas.js

Catalog: https://docs.google.com/document/d/1VpFhfYEekz9x2Oe02FAlw8xYVmisHkmrt2NxCxDHdxw/

Added hungry hustlas catalog

---

src/importer/mastononkaps.js

Catalog: https://docs.google.com/document/d/1XwH1785exI1NCfr3M-ZtkcTxDe4fICVP0Tmbvg00HXQ/

Added mastononkaps catalog

---

src/importer/rathcaps.js

New catalog: https://docs.google.com/document/d/1mX-wUILSjmOGULIju5SKD3zKn7VE9hLl2BHgZZPTnG0/edit

Updated Rathcaps catalog

---

src/importer/trmk.js

Update trmk discord, website

---

src/importer/picaps.js

https://docs.google.com/document/d/1SyKkp4PhrCCealubpwHz5GUWfZejQGspXmgWW2T0qzw/edit#

Add Picaps

---

src/importer/rejeckkaps.js

Catalog: https://docs.google.com/document/d/10EGmT_ifrjOuqFENtfrxfWljiR8etxHdmyU-gLAhfQw/

Added rejeck kaps catalog

---

src/importer/okeydokey.js

https://docs.google.com/document/d/1_khNYhY3YlyeRK9Tok3qDQ-FJU-lBittK0fsNiLbWhI/edit?usp=sharing

Add okeydokey

---

src/importer/blackmagecaps.js
src/importer/okeydokey.js

https://docs.google.com/document/d/1uIATE-QeIMq_kZnXi_EVfZZoHpM3dmc2woBekYV4L2A/edit

Add Black Mage Caps

---

src/importer/bhomasscaps.js

Catalog: https://docs.google.com/document/d/1N8RgbXu7BVt1uXa38uyJMMQJ5FzqxgmvqktNpp9MA_Y/

Added bhomass caps catalog

---

src/importer/madlabskeycaps.js

Catalog: https://docs.google.com/document/d/176oXSO83YXhYkVDBpoanyiroWaqXq7SmOY8OQfO6bfY/

Added mad labs keycaps

---

src/importer/ochre-moss.js
src/importer/sirreal.js

Ochre + Moss: https://docs.google.com/document/d/1r3HhhDyLTnLJrDb5kpCazx_-j7SwOk9GHl9G-zek-N0/edit?usp=sharing
SirReal Caps: https://docs.google.com/document/d/1EllRzUrKjgARXPRYy180K9ru_aYgVG89DQ8CxxFViRc/edit?usp=sharing

Add Ochre + Moss, SirReal Caps

---

src/importer/dwarf-factory.js

https://docs.google.com/document/d/13sG3yOqu-7AFkHRcSulp_Iwm0N4g9SOKwSi0vWxx2yA/edit?usp=sharing

Dwarf Factory

---

src/importer/bogwitch-brie.js
src/importer/psycho.js

Add Psycho Keycaps, Bogwitch Brie

---

src/importer/objectgarage.js

Catalog: https://docs.google.com/document/d/1RWKUmcfE9XYslR5GDldajorjTxCqBVM0UE7wBxeB6G4/

Added object garage catalog

---

src/importer/qqaps.js

Catalog: https://docs.google.com/document/d/1D1Pt_Jp0Mm35O0a2vFQ6mh2UzcjT1JBWxjqUcc2tSBY/

Added qqaps catalog

---

src/importer/sublymekeys.js

catalog: https://docs.google.com/document/d/1Q6lOKRofrQXEFxQddLXDYC2B_9rZ6pd7qbUfueiranI/

Added sublymekeys catalog

---

src/importer/meof.js

https://docs.google.com/document/d/1Gb0HeMF0jE8wfN6sUJEsVRcWjC88VmWJQnABIKEv28o/edit#

Add meof.caps

---

src/importer/miroticaps.js

Catalog: https://docs.google.com/document/d/1tu1aiEHLDCMX3E7nv8ikNl60o-xv4fFdar8krU6Cstc/

Added miroticaps catalog

---

src/importer/gooey.js

Heyo!
I've exhausted my patience with Google Docs, so I've adapted the work by Zekth, GreatWizard & Nachie into a somewhat more generalized -- i.e. all of the variables have been pulled out of the logic -- custom importer for complete (except for the artisan, sculpt & colorway IDs) JSON catalogs.
Please let me know if there are any issues here, either in the code itself or the general concept. I'm happy to make any changes or discuss as needed.
One thing that could be an issue (specifically for my catalog) is that I've capitalized my artisan name here. It is currently all lowercase on the site, but I'd like it to be in capital case.
As always, thank y'all for all your work on the archive and for your time!

Custom Gooey Keys importer

---

package.json
src/discord-update-report.js
yarn.lock

• Added use of discord embeds, so future (more expansive) modifications can be made in the future.. 
without use of embeds a lot of features within discord web-hooks and bots cannot be used.. In which we have reached some point where such features.. that embeds allow would be very viewing friendly!
• Added hyperlink, linking to the Catalogs of which are listed!
Up to my testing with both, discord bots and discord web-hooks, this shall work accordingly..

Adding use of embed and hyperlinks for ease, of viewing and checking..

---

src/importer/ezkeys.js

https://docs.google.com/document/d/1NGfIh3aAU5CwE425oshmoUBEjs11In1j7pVUHrov8Vs/edit

Add EzKeys

---

src/importer/bkmcaps.js

Catalog: https://docs.google.com/document/d/1LinZIytdrqwGE7H3TBWeIrj6ICQ_2DzWVm2Mmk904Y8/

Added bkm caps catalog

---

src/importer/crystal-pieces.js

https://docs.google.com/document/d/1cR7ceg-E5K8D-AxTq4-9Wm3s_qeUTFjTcJIJBWBZnJU/edit

Add Crystal Pieces

---

src/importer/ddor.js

https://docs.google.com/document/d/1x6w725FhjkOUwu3ZMYMMtDgZg9404CdexIYKgQdBE8Y/edit

Add DDOR Studio

---

src/importer/gaia.js

https://docs.google.com/document/d/1EJ8IodjlMPG-TtmKwTZuCvIQYO9uuD_phTnMiNqjh4s/edit

feat: add Gaia’s Creature catalog

---

src/importer/krapshop.js

catalog: https://docs.google.com/document/d/1YUGAY-ZxuFC9dCF_fXZ8tVW8T0LSN9FlLjxRTscnoVc/

Added krap shop catalog

---

src/importer/miniworld.js

https://docs.google.com/document/d/1K2IP5lV4-6PLuJcFLhpR-gJAqHhxY7baxZSG2DaSPvo/edit?usp=sharing

Add Miniworld Studio

---

src/importer/blank-works.js
src/importer/ddor.js

https://docs.google.com/document/d/1ehAQBiLvDzM6FUqAKxP2kpJFEQaDnq3yR75TuM0L8vY/edit

Add Blank Works

---

src/importer/lunakeycaps.js

catalog: https://docs.google.com/document/d/1AV5u4TtQY2iKOisKygGIn7IYFGzcqU9hhjqI76UzkbM/edit

Added luna keycaps catalog

---

src/importer/jellykey.js

https://docs.google.com/document/d/1Y9hJ5WgjSjXhKEpeLudk542Mj_P0B9aJt56CLdf5Oas/edit

Add Jelly Key

---

src/importer/nuhz.js

https://docs.google.com/document/d/1-BcprHM7kp7znXKbCKrcCnKbd2q5GvX4UI8qod5J3rA/edit

Add Nuhz Caps

---

src/importer/kapsule-lab.js

https://docs.google.com/document/d/1aY15g26g_KGpSfBv5XPPeXPFnP9Lq9xgJUlF3IVsm_c/edit

Add Kapsule Lab

---

src/importer/sinpracaps.js

catalog: https://docs.google.com/document/d/11mcz58aQkOb72h70LZelv9teAqdUrL-o57I0fIA2VFg/

Added sinpra caps catalog

---

src/importer/theboxkeycap.js

https://docs.google.com/document/d/1R-0hie5BZ66Uqv-FILFqHEfanQPAYwpBPMGqFWVGR_A/edit#

Add theboxkeycap

---

src/importer/keyzen.js

https://docs.google.com/document/d/1YljdTx25HavIPtY4ZFNWT1eULVTbCS-i1bUYjEVjwU4/edit

Add Keyzen

---

src/importer/craftkey.js
src/importer/monstera.js

https://docs.google.com/document/d/1BVfiGhTs-8dCm2u_KpAxKGALy9X7CT94rDljgyFl0uE/edit

Add Monstera Keycaps

---

src/importer/stone-keys.js

https://docs.google.com/document/d/1kVAbEYLLsFT4y6k0b7A1aenvKOtPzX93cSDXqC_f2eQ/edit

Add Stone Keys

---

src/importer/plastic-d2.js

https://docs.google.com/document/d/1dHvxJWBcyuM4mrPUu3Hinqn-Ue1au9INzfljCa_Ue7I/edit

Add Plastic D2

---

src/importer/landcaps.js

https://docs.google.com/document/d/1qDHsR0Y2U0W_pBPgtvB_i_xh09a1VVInbg3rK7al7Ug/edit?usp=sharing

feat: add LandCaps

---

src/importer/captomaniacs.js

New url: https://docs.google.com/document/d/14VMtz60UJoIfm-Lq66lqJjpwwofk4ZlREq4JKSMEFPo/

Updated captomaniacs URL

---

src/importer/klaykaps.js

catalog: https://docs.google.com/document/d/1U_Te4TY5Nxwme5CjnFMd3tGqSYXJxrkYK7c7VlkI2MU/

Added klaykaps catalog

---

src/importer/nibbnubb.js

catalog: https://docs.google.com/document/d/1VDaL0vyFLSMyfmw2k-Aa3RleuEU9o3H6JPiV33zTDy4

Added nibbnubb catalog

---

src/importer/matae-keycaps.js

https://docs.google.com/document/d/1PZ-Rf46GQiDdG3E6R837QEknkapMMbmqPPXnq0l2vbg/edit#

Add Matae Keycaps

---

src/importer/myth-caps.js

https://docs.google.com/document/d/1-CkxK7KHUIy9gzJkguA36eC463cBHkNeGfgLa40BKVE/edit?usp=sharing

Add Myth Caps

---

src/importer/della-key.js

https://docs.google.com/document/d/1beOD7ijqhqVV3FaWnvMF08FQ5KQGO-PENN5hohyrEm4/edit

Add DELLA KEY

---

src/importer/chickencap.js

https://docs.google.com/document/d/1pkiYq1bxrHYqydM7yj9dKZPG8vC8fNBMGOrQGSyT7qQ

Add ChickenCap

---

src/utils.js

Update regex to support more date formats
- DD MMM YYYY, MMM YYYY, YYYY
- DD MMMM YYYY, MMMM YYYY, YYYY

Support more date formats

---

src/importer/json/yu.keys.json

https://docs.google.com/document/d/1OENdni0rgtO6J2cYKqD1ccrubulXDn-bCHt26TG4nHU/edit

Add Yu.Keys

---

src/importer/json/ackeys.json

https://docs.google.com/document/d/1-pP9xJMH55xNGq3waZb6n5x0t6vNX9aqsQAUKaXLfv8/edit?usp=sharing

feat: add ACkeys

---

src/importer/json/vice-caps.json

https://docs.google.com/document/d/1WR23MyXbLOAi0Vh6UoeRQqmZ2UsilJNVunw0Y_Hf9fU/edit

Add Vice Caps

---

src/importer/json/namong.json

https://docs.google.com/document/d/1vqBrU8VL6Mf6dmRRETjvo5d23HCQuwBQsG1m7w9ClmA/edit?usp=sharing

Add Namong

---

src/importer/json/mozicaps.json

https://docs.google.com/document/d/1fq6yWk8Gsye4U5M1Fr7SWqTrBMBOx88855RhkUvC10k

Add MOZIcaps

---

src/importer/json/driiip-keys.json

Add DRiiiP Catalog: https://docs.google.com/document/d/1hIFJszQMhrQgfo0wjpplbWcvcWIAs5y3HwfwrbFI9e4/edit
```shell
- DRiiiP Keys
---- Lil'Dentist : 10 colorways
---- Ronron : 6 colorways
---- Olive : 7 colorways
---- Bleblublubleu : 1 colorways
```

feat: add DRiiiP Keys

---

src/importer/json/jusherhoe.json

catalog: https://docs.google.com/document/d/171XoC3BAC13iMQlAJ85impbm-jj7irgCDZwGwYfNTfc/

Added jusherhoe catalog

---

src/importer/json/arkeys.json

https://docs.google.com/document/d/1q__LoSd2vlzY95KKp0TStW2bA3XBPvKZcOQPrKprQh0/edit?usp=sharing

feat: add ARKEYS

---

src/importer/json/phangkey.json

catalog: https://docs.google.com/document/d/1awYbT9shWhsI6wnpXVUozJxwQjFbiYXhTNNPQOCeAvE/

Added phangkey catalog

---

src/importer/json/cattocaps.json

catalog: https://docs.google.com/document/d/1Lb8WPFy3mCNnt49yAkhJwqQugKJdo11PBLJfeMfodHI/

Added catto caps catalog

---

src/importer/json/mubai.json

https://docs.google.com/document/d/1xWL_Y12WVbijqpWek8dIYPAAoHns6YBb3OPrYBZNryY/edit#

feat: add MUBAI

---

src/importer/json/death-dealer.json
src/importer/json/echopp-caps.json

https://docs.google.com/document/d/1ffA0_Y8zC68So3XPeoP41JsAC2M68RSRfNAxzaFdslY/edit

Add EchoppCaps

---

src/importer/json/kb-keycraft.json

https://docs.google.com/document/d/12mZSYQV5qtEyRFm-ojm3Bu6B1bX-pePAxoyz-5cE-v8/edit

feat: add KB Keycraft

---

src/importer/json/bungkee.json

https://docs.google.com/document/d/1n1Wcp3UNo6M161050sW-tFL1Wn7tgRYpG3CeKLo1jn4/edit

feat: add Bungkee Caps

---

src/importer/json/jibii.json

https://docs.google.com/document/d/1KTJ1Up_7Jjr81xbjNSzNswNBXnfSgOsEZr4wc2ODEEo/edit

feat: add Jibii

---

src/importer/json/8o8keys.json

catalog: https://docs.google.com/document/d/15rWfoHxCHXtWuRjZYYX6u98H9IG0U4AugsCEHDKzLas/

Added 8o8keys catalog

---

src/importer/json/mfc.json

https://docs.google.com/document/d/1Q4JOAQQIY3iat1tBhDXs8aT8hw0JEk92aJlVRxRI3bY/edit

feat: add MFC

---

src/importer/json/kiyokaps.json

https://docs.google.com/document/d/1eC4oLh3QZ-4kUeejnhWTPEnh7_D2pqp7CsQDziXf6uQ/edit

feat: add KiyoKaps

---

src/importer/json/driiip-keys.json

See https://www.instagram.com/driiip_keys/

feat: add instagram url for driiip keys

---

src/importer/json/zero.json

https://docs.google.com/document/d/1pJjELN0W1faMi0kcwyrc9do4XwXorlruZfDVMh9Av3Q/edit

feat: add Zero Keycaps

---

src/importer/json/key-capital.json

https://docs.google.com/document/d/11s6cWXG1-_m0x4JpFF0kUD716laUxKUhtIzO0r_OP1U/edit

feat: add Key Capital

---

src/importer/json/zellkey.json

https://docs.google.com/document/d/1SS3g7HabIxQhRCb9_dEKRBWkXF24XyeELFtlf09hOdQ/edit

feat: add ZellKey

---

src/importer/json/azi.json

https://docs.google.com/document/d/1ysgu4CCl_hRjyGUqJbgEJrC69MYOcy5Mo0BgR6457fk/edit

feat: add Azi Keycaps

---

src/importer/json/bogancaps.json

catalog: https://docs.google.com/document/d/1n0ptNP1tZHnMtpJAI_s_qlnvulYl9SZBJwkCHdU5vHI/

Added bogan caps catalog

---

src/importer/json/1of1keycaps.json

catalog: https://docs.google.com/document/d/1p1r9wy1Url3ilU-Tn4ear2gtDtKsIkbG1WlCTTJjOKQ/

Added 1of1Keycaps catalog

---

src/importer/json/kin-caps.json

https://docs.google.com/document/d/1oSC6767-PT4EzL_qaj8Q1kFWyl64QqzH40Fgg_jzadw/edit?usp=sharing

feat: add Kin Caps

---

src/importer/json/artzeikaps.json
src/importer/json/kin-caps.json

https://docs.google.com/document/d/11l5gZpMa9dCoSm3RYnhKc0YXSpSm__WIfLyQsg7asto/edit

feat: add Artzeikaps

---

src/importer/json/daisyskull.json

catalog: https://docs.google.com/document/d/12mtyujoMo0dB2iiWR4utBunOAXyIeGEClFuYHEx0Fzg/

Added daisy skull studio catalog

---

src/importer/json/cantoclicks.json

https://docs.google.com/document/d/1AOw5Rczpa5NEohg5DQScnqi5Efvc6R8z4F46JIYoOP0/edit

feat: add Cantoclicks

---

src/importer/json/2tcraft.json

catalog: https://docs.google.com/document/d/1aWFIxJmIVeJDZH1b_1TEWJBUOcqqsAzUJ6KgEwp069Y/

Added 2tcraft catalog

---

src/importer/json/asianjoyco.json

catalog: https://docs.google.com/document/d/1s02KAr-bTy2ZHR6YU4O2NLqLNxM9cAeJ9HrZ1Q3uWYI/

Added asain joy co catalog

---

src/importer/json/anomalycaps.json

catalog: https://docs.google.com/document/d/1zc0G7J3wd6sdOFcdLokOmom-mQmgm6gzhXUHZO8r3kI/

Added anomaly caps catalog

---

src/importer/json/atoworks.json

catalog: https://docs.google.com/document/d/1rye8X24IRtPhhXHcuPhisZUs16oKWM7zeqtjBU_SSPg/

added atoworks catalog

---

src/importer/json/keycapcustoms.json

catalog: https://docs.google.com/document/d/1AkBXbURT4fcY65uW0HgU4lHXS0_YqGmdJoXUz8kXWCs/

Added keycapcustoms catalog

---

src/importer/json/smyleey.json

https://docs.google.com/document/d/1pbpzRVKy4kv4yRc5Ztj8M6H-FlHCID4nASttnwn1pYE/edit?usp=sharing

feat: add Smyleey x Godmade

---

src/importer/json/ezkeys.json

fix: update EzKeys database

---

src/importer/json/kug.json

catalog: https://docs.google.com/document/d/1_GW1c005RK7X2olNW2flNdkJEcM9_TOZ1e4ONUfHUYU/

Added KUG catalog

---

src/importer/json/from-scratch.json

https://docs.google.com/document/d/1xeyfq3YJTwOhGnUBFFZLMCj5S9D7gUrd6Umf12GPAzA/edit?usp=sharing

feat: add FromScratch Caps

---

src/importer/json/omega.json

fix: update discord

---

src/importer/json/avocaps.json

https://docs.google.com/document/d/1hOGoAtIWAxII-y3X8cSJ4hKLHOlrdhkc6iObC0DzWt4/edit

feat: add Avocaps

---

src/importer/json/triplenightkaps.json

catalog: https://docs.google.com/document/d/1q_LPkHEAF7Hp-_jBul6foA65RC6LHPKVeN9ExqghsrQ/

Triple night kaps catalog

---

src/importer/json/clackeys.json

https://docs.google.com/document/d/1X05Agu-mAkGAuTwkrdX6TZJkSe42djf_aJA7U1GlB-M/edit

feat: add Clackeys

---

src/importer/json/sinpracaps.json

catalog: https://docs.google.com/document/d/1dQebU21O42zU2Qo8Sr4ZioGxYNwpYFptGopxrG4phn8/

Added simpra catalog

---

src/importer/json/sondercaps.json

catalog: https://docs.google.com/document/d/1nZEhuaS3rNaGzJieik-EEhOtnLtTHwrbIOxc81uyKI8/edit

Added sonder caps catalog

---

src/importer/json/mariotheguy.json

catalog: https://docs.google.com/document/d/1TJ-cV5VpMDm0qvF5bLE1cyp_UtZ0mMUK3XFhUXqfEmo/

Added mariotheguy catalog

---

src/importer/json/kookcaps.json

catalog: https://docs.google.com/document/d/1RI8quPYaJnGxMVBc1fTw_jL4skru4b--V7ORXfmaszw/

Added kook caps catalog

---

src/importer/json/inkblot.json

catalog: https://docs.google.com/document/d/1jE94XFa7QZPMtwjsbLwqNkgwGsFJNsyAEjdSlDcBaCE/

Added inkblot catalog

---

src/importer/json/savecaps.json

catalog: https://docs.google.com/document/d/1CmBPk8MTC3fLeUczX6CA0KeQGRZqLEKHS9AOC72OjWk/

Added save caps catalog

---

README.md
src/utils.js

Allow for count header

---

templates/README.md

Now I know for the next time I randomly decide to add a feature no one asked for

Update the template

---

src/importer/json/zouabi.json

catalog: https://docs.google.com/document/d/1bbQYDOFizNYAt6StvoxHB7sbIzvY2i-PlFNRctjngg4/

Added zouabi catalog

---

src/importer/json/unknown-keycaps.json

https://docs.google.com/document/d/17Bhy7YSkXQQO2YC8hvCYsxbRprgMMNTpuMCFnFyDrts/edit#

add Unknown Artisan Keycaps

---

src/importer/json/pixart-valley.json

https://docs.google.com/document/d/1DDUof0CPmirwcCbNGSkqX-_R4onwfbZQhuqHZqsTpHw/edit

feat: add Pixart Valley

---

src/importer/json/mystic-world.json

https://docs.google.com/document/d/1oeXo0YesQfjJSZ9USDUd_fIQuib5i5m6LNfacSR-1T4/edit?usp=sharing

feat: add Mystic World

---

src/importer/json/archetype.json
src/importer/json/bhomasscaps.json
src/importer/json/binirias.json
src/importer/json/boop.json
src/importer/json/brewcaps.json

- update some expired discord invites
- update some website urls

fix: update some discord invites, website url

---

src/importer/json/macher.json

https://docs.google.com/document/d/1nSusf9xLZErFgheGcr7q5PsJYVqTVEyDUzKYWxR6PQ0/edit

feat: add Macher Studio

---

src/importer/json/janky.json

https://docs.google.com/document/d/1nT-vBKIXCFuAPPUCewAcUcwGt9-1Bedkyd4CGdjQfBM/edit

feat: add Janky

---

src/importer/json/lazercaps.json

https://docs.google.com/document/d/1Q5o4ct05fGqAyo5QnaeaF0hWtJhRyuT5VE5CIAPW24Y/edit

feat: add LAZERCAPS

---

src/importer/json/stupid-fruit.json

Yes please officially add my catalog

add stupid fruit caps

---

src/importer/json/t-art.json

https://docs.google.com/document/d/1rAusxiqfPBB_5S7zeEOYX1TJNu4ehcZdxG8jmLLN5Ds/edit?usp=sharing

feat: add T-Art Universe

---

src/importer/json/animech.json

https://docs.google.com/document/d/15IRx6bobdBXas3CZT81qexe-qFcK6t9dgz3IVXkTVPw

feat: add Animech

---

src/importer/json/kitanncaps.json

catalog: https://docs.google.com/document/d/1OKMEDz4c7rILX8aiH332n-wW3PjIN3meKu5ZXStgDTs/

Added kit ann caps catalog

---

src/importer/json/rawstudio.json

catalog: https://docs.google.com/document/d/1gYRLcLvlUlh5oKvMuLWh0xz3QQpxw6OVtTzefJa3FDY/

Added raw studio catalog

---

src/importer/json/beetlecaps.json

catalog: https://docs.google.com/document/d/12T82CMnIwcdEg36bIrE9hlyi4Ikd15kutuRbYsOFKnw/edit

Added beetle caps catalog

---

src/importer/json/bg-caps.json

https://docs.google.com/document/d/1M37Dyc3mBFYEEJTbi9ol_YSFHQ9MPScX0J0SH0nTSEo/edit

feat: add BG Caps

---

src/importer/json/kuco.json

https://docs.google.com/document/d/1EV8GvLdbn5Zh9NtU4uGPiswaqi0EGm5uamAjSuWDbiY/edit

feat: add Kuco

---

src/importer/json/gsk.json

- update discord url
- remove tab operations as quicklinks table removed

update GSK db

---

src/importer/json/keyzen.json

https://docs.google.com/document/d/19TEE9_vnw-tzcigMxL-8ILUAmkkEWPrUQc4A9s7IkbE

fix: update Keyzen docId

---

src/importer/json/zuno.json

https://docs.google.com/document/d/10Qsh838fnc0tO-7cPTtXCvXoQ-bMGwfZR_l0COHXGoU/edit#

feat: add Zuno Studio

---

src/importer/json/maisonofthewest.json

catalog: https://docs.google.com/document/d/1HUaZBU-PDmvgBQCW7k9y9YdcI0pZ5S5_91jab7n539o/

Added maison of the west catalog

---

src/importer/json/clover.json

catalog: https://docs.google.com/document/d/18VXOqRajYKnkxWzlUVFf2vIm3JvqBVZ8W5rUs0cqVPI/edit

Added clover catalog

---

src/importer/json/zomgkey.json

catalog: https://docs.google.com/document/d/1HhdYF-daQQdMQdY4JNWWv6SdPRhImsZ6aVoa8UIQkSc/

Added zomgkey catalog

---

src/importer/json/almondcaps.json

https://docs.google.com/document/d/1VwfhlloIpnE_AbmKb2JEfx13SGMKusSZfecHr3zeBEs/edit

feat: add ALMONDcaps

---

src/importer/json/spectrum-studio.json

catalog: https://docs.google.com/document/d/1N9roTfgFicA9wQMCzNbiNBeOQw_SDDOKv7TWVdosfMI/

Added spectrum studio catalog

---

src/importer/json/spectrum-studio.json

Reverts keycap-archivist/database#256

Revert "Added spectrum studio catalog"

---

src/importer/json/aerokeys.json

catalog: https://docs.google.com/document/d/1EV-U7IQNdzmCElmV19TROyd3lSa2PPIFgCdjFkMrMFM/

Added aero keys catalog

---

src/importer/json/wildkeycaps.json

catalog: https://docs.google.com/document/d/1E4BbJAZYV0aRR8zCtrD9DI9vRWM3jD1EbLBsdtFl2-4/

Added wildkeycaps catalog

---

src/importer/json/varsitykeys.json

catalog: https://docs.google.com/document/d/1uKCfFhB6auBi7zTUmFY-A7VkWkh1w5h5iPTvAVaNxuA

Added varsity keys catalog

---

src/importer/json/panduuh.json

catalog: https://docs.google.com/document/d/1K6KDWr_6c91n-3DkhybqseJNEvZT9_0u9HNVps6WV90/edit

Added panduuh caps catalog

---

src/importer/json/blanksy.json

catalog: https://docs.google.com/document/d/1tlH37yLHd9HnHJMF_rHTIdX64kkwhm_WvtC3vPRXa1E/

Added blanksy catalog

---

src/importer/json/jellycap.json

catalog: https://docs.google.com/document/d/1yuo_c4hpBYWW8zryZXMi15Byzj-AR8iVWzx1QWT5O8k/

Added jellycap catalog

---

package.json
yarn.lock

Reverts keycap-archivist/database#337

Revert "build(deps): bump sharp from 0.32.4 to 0.33.1"

---

src/importer/json/basilkeys.json

https://docs.google.com/document/d/1azIr0Ok_QxYpQsrZ1S0bX48rXI1v9DwzvETTSWHxdko

Add BasilKeys

---

src/importer/json/d-slime.json

https://docs.google.com/document/d/1ws2UWWPH2DzJJR4jo0vLyfOUenc4QpkwL-xt0QnumhE/edit

feat: add D.Slime

---

src/importer/json/wheat-keys.json

https://docs.google.com/document/d/1D4fIHx6vT3ZWPPdyKyfYrl4xc2ajbWETJP98Rk7HQOQ/edit

feat: add Wheat Keys

---

src/importer/json/alheckz.json

https://docs.google.com/document/d/1sPgSv9qsAgzIiDnhD92KphJSp5vYmICx-_Gp00qbrhY/

feat: add alheckz

---

src/importer/json/haon.json

https://docs.google.com/document/d/11ADpKXXtrG0ON4X1hjvVAvFZpB8HJlSPskIZtaTDUi4/

feat: added haoN

---

src/importer/json/apothecary-caps.json
src/importer/json/mfcaps.json

Title:
apothecary: https://docs.google.com/document/d/1291TtygV3rFf97ii9JVTk2ctg7vL7ztRWhvlEy_-g-w/edit
MFCAPS: https://docs.google.com/document/d/1nslOUvKblaJqbTGDfV1zFzhfq7q5wD_VyrXhIEKs614/edit

added json for apothecary and mfcaps

---

src/importer/json/amano-studio.json

https://docs.google.com/document/d/1DN-q8DMa9fpZDle-S4tr_3kGelZxoC46xanykcYjvbA/edit?tab=t.0

added amano studio doc

---

src/importer/json/haon.json

add discord for haon

---

src/importer/custom/alphakeycaps.js

Add pintut

---

src/importer/json/emotikeys.json

Add emotikeys

---

src/importer/json/textstyles.json

Added json file
Doc: https://docs.google.com/document/d/10RefSn-ouqWctFOwTEcM1MGLeF729aTnVpGAmOcS3Rg/edit?tab=t.0

feat: added textstyles
